apiVersion: v1
kind: Service
metadata:
  name: clusterpuppy-{{ .Release.Name }}-service
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.httpPort | required "httpPort required" }}
      protocol: TCP
      targetPort: http
      name: http
  selector:
    {{- range $k, $v :=  .Values.global.appSelector | required "appSelector required" }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}  
