/*
 * KubePuppy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubjectRoleBindingsInner struct {

	RoleBindingId string `json:"roleBindingId"`

	RoleBindingName string `json:"roleBindingName"`

	RoleId string `json:"roleId"`

	RoleName string `json:"roleName"`
}
