// See: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go-gin-server/routers.mustache

/*
 * KubePuppy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func AddRoutesToRouter(router *gin.Engine) {
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/api/v1/",
		Index,
	},

	{
		"ValidateCertificate",
		http.MethodPost,
		"/api/v1/certificate/validate",
		ValidateCertificate,
	},

	{
		"DeleteRole",
		http.MethodDelete,
		"/api/v1/role/:roleId",
		DeleteRole,
	},

	{
		"GetRole",
		http.MethodGet,
		"/api/v1/role/:roleId",
		GetRole,
	},

	{
		"ListRoles",
		http.MethodGet,
		"/api/v1/roles",
		ListRoles,
	},

	{
		"DeleteRoleBinding",
		http.MethodDelete,
		"/api/v1/roleBinding/:roleBindingId",
		DeleteRoleBinding,
	},

	{
		"GetRoleBinding",
		http.MethodGet,
		"/api/v1/roleBinding/:roleBindingId",
		GetRoleBinding,
	},

	{
		"ListRoleBindings",
		http.MethodGet,
		"/api/v1/roleBindings",
		ListRoleBindings,
	},

	{
		"GetSubject",
		http.MethodGet,
		"/api/v1/subject/:subjectId",
		GetSubject,
	},

	{
		"ListSubjects",
		http.MethodGet,
		"/api/v1/subjects",
		ListSubjects,
	},
}