/*
 * KubePuppy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteRole - Deletes the specified role (either cluster or namespaced).
func DeleteRole(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRole - Shows details regarding the specified role (either cluster or namespaced).
func GetRole(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListRoles - Lists all roles (both cluster and namespaced).
func ListRoles(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
