/*
 * KubePuppy API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetSubject - Gets details regarding the specified subject.
func GetSubject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListSubjects - Lists all subjects.
func ListSubjects(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
